// #include <iostream>
// using namespace std;

// int main()
// {
//   int t;
//   cin >> t; // কতটি test case আছে

//   while (t--)
//   {
//     long long n;
//     cin >> n;

//     if (n == 0)
//       cout << 1 << endl;
//     else
//     {
//       int cycle[] = {6, 8, 4, 2};
//       cout << cycle[n % 4] << endl;
//     }
//   }

//   return 0;
// }

// #include <iostream>
// using namespace std;

// int main()
// {
//   int t;
//   cin >> t; // কতটি test case আছে

//   while (t--)
//   {
//     long long n;
//     cin >> n;

//     if (n == 0)
//       cout << 1 << endl;
//     else
//     {
//       int cycle[] = {6, 8, 4, 2};
//       cout << cycle[n % 4] << endl;
//     }
//   }

//   return 0;
// }
